### ISSUE TITLE
Rebuild website

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons.github.io#1]
I've been thinking about our website for a while, and there's a few points that could need improvement in my opinion:

* difficult to contribute (as in: I have no idea where the source code is)
* uncertain hosting (who is hosting the website, are we dependent on a single person?)
* not responsive / mobile ready

I'm proposing to tackle the first two issues by moving to a static site generator, which makes it trivial to host the webpage. For example using GitHub-Pages. Also contributing is much easier, since the source code is just another repositiory here on GitHub.

The third issue can be fixed by redesigning the website and using a more modern approach to things.

Yesterday I started work on a potential replacement for the current website. Keep in mind, at this point I've mostly setup a static site generator (Lektor in this case, written in Python) and slapped some Bootstrap styles on it. That's why the design still screams "Bootstrap!" right now. This is completely work-in-progress, trying to figure out content & structure, with less focus on styling and eye-catching things.

I'll probably write some more thoughts later this evening. Until then, here is the current repository:

Repository: https://github.com/squiddy/unknown-horizons-website
Current build: https://squiddy.github.io/unknown-horizons-website/

**Comment by squiddy** [comment]
Started working on the styling, the lower part of the homepage for now. I've deployed the new build to my repository.

![currentbuild_0202](https://cloud.githubusercontent.com/assets/50333/22571077/7033307a-e99e-11e6-8817-5824c1db4474.jpg)

**Comment by LinuxDonald** [comment]
@squiddy what about to merge your repo into this here one? I would like to help on it an provide content. I want to fast the old one because completly outdated software.

**Comment by squiddy** [comment]
@LinuxDonald If you think the approach I'm proposing here is worthwhile (I haven't gotten feedback about that yet) then yes, we could merge. However, it isn't really a blocker for contributions. My repository is public. :)

**Comment by squiddy** [comment]
And we haven't even talked about the things we want to support / not support. For example, what about blog comments? Sure, I've integrated disqus, but if that's the right fit I don't know.

**Comment by squiddy** [comment]
Disqus ist going to enable ads in the free version permanently. https://blog.disqus.com/our-plans-for-2017

Edit: damn you autocorrect

**Comment by citizenjules** [comment]
I prefer to keep it simple. Why not just a link or embedding a thread of the forum? So we won't have two different locations to discuss about news.

**Comment by squiddy** [comment]
> Why not just a link or embedding a thread of the forum?

That's probably the best solution to start with. The last 5 news posts had 3 legitimate comments, so moving that to the forum and/or github is better.

If later, for some reason, we need to provide a quick&easy way for people to comment we can re-evaluate other solutions.

**Comment by korolr** [comment]
I moved the content from the old site and not much corrected design. He added links to social networking and downloading. What else can you do?
![screenshot from 2017-03-05 22-13-55](https://cloud.githubusercontent.com/assets/11715165/23589454/73195e42-01de-11e7-9404-77c09ad57a24.png)
![screenshot from 2017-03-05 22-14-16](https://cloud.githubusercontent.com/assets/11715165/23589455/731a95f0-01de-11e7-9011-3e36ade4fb59.png)
![screenshot from 2017-03-05 22-14-37](https://cloud.githubusercontent.com/assets/11715165/23589453/73193f66-01de-11e7-9e46-b70baf9e6ce7.png)

**Comment by squiddy** [comment]
Sorry, I don't understand what you are trying to say.

**Comment by korolr** [comment]
:) I created the Pull request where 
- Added links to social networking and downloading
- Moved the content from the old site
- And fixed a lot of design
How else can I help you ?

**Comment by squiddy** [comment]
Oh, I see. That's awesome. :+1: I may not find time today to look at the changes, but I will get back to you tomorrow.

**Comment by squiddy** [comment]
I moved the code from my repo into this one. As of now, travis CI will automatically update the webpage (in the master branch) whenever the source branch is updated.

**Comment by stubb** [comment]
We should think about the social media stuff. Are we able to provide a mechanism via the static site to forward published news to them, like we did in the past with the old page? Btw. having the old red seal buttons again would be lovly

**Comment by squiddy** [comment]
I guess one could hook into the deploy logic of lektor to make that work.

Am 08.03.2017 10:00 nachm. schrieb "Kilian Köppchen" <
notifications@github.com>:

**Comment by LinuxDonald** [comment]
Now we need an nicer gallery and maybe better download section with an how to for linux?

**Comment by LinuxDonald** [comment]
I think that could be closed. Because Github site is now online :)

**Comment by squiddy** [comment]
Oh cool, did not expect that.
