### ISSUE TITLE
Add on the Topbar Forum Link

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons.github.io#10]
Add on the Topbar Forum Link:
Four users that want help it where easier to find fast the forum instand first clicking on Support.

@squiddy could you maybe do this?

**Comment by squiddy** [comment]
Sure, I'll do that either late tonight or tomorrow.

**Comment by LinuxDonald** [comment]
Link is broken: http://unknown-horizons.org/https:/forum.unknown-horizons.org

**Comment by squiddy** [comment]
That's what I get for doing that late at work. It's probably the template URL filter. Will fix it in an hour.
