### ISSUE TITLE
Link on forum site results in "Page not found" error

### ISSUE THREAD

**Issue by BevapDin** [unknown-horizons/unknown-horizons.github.io#13]
On the forum site https://forum.unknown-horizons.org/ is a link labeled "Imprint" (on the top, right of the "Donate" link). Following it leads to http://unknown-horizons.org/site/index.php?page=imprint which returns a "Page not found" error site.

**Comment by LinuxDonald** [comment]
Thx for the report we will fix this :)

**Comment by LinuxDonald** [comment]
Should be fixed now. But we have server problems. Forum is down.
