### ISSUE TITLE
Use https

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons.github.io#16]
Github pages just gained https support for custom domain names!
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
We should set this up for unknown-horizons.org
Who has access to the DNS records?

**Comment by jmdejong** [comment]
@nihathrael I believe you are the registrant. Could you update the A record to the new ip's?

**Comment by LinuxDonald** [comment]
Done
