### ISSUE TITLE
unknown horizons forum cant create account

### ISSUE THREAD

**Issue by tomlukeywood** [unknown-horizons/unknown-horizons.github.io#17]
I am asked to enter a confirmation code which should be displayed in an image however no such image seems to exist so I am unable to create an account

see this image: http://92.19.232.58:81/owncloud/index.php/s/I6Su9XiNN5py8tT

I also tried to contact the board administrator using the form on the website however this gave an error when I tried to send the message which is why I am posting here.

**Comment by LinuxDonald** [comment]
Sorry i think i need to setup an new one. because i cant reach the Server Admin and i dont Own the domain too. But its on my todo list to setup an new domain and new forum.

**Comment by LinuxDonald** [comment]
Forum should work adin. Please give me your username. Than i can activate our account.
