### ISSUE TITLE
"About" and "Media" pages are missing when entering from forum

### ISSUE THREAD

**Issue by CornerLord** [unknown-horizons/unknown-horizons.github.io#21]
Steps to reproduce the problem:
1. Go to [https://forum.unknown-horizons.org/](url)
2. Click either "About" or "Media"
3. "About" redirects to [http://unknown-horizons.org/game/](url) and "Media" to [http://unknown-horizons.org/media/screenshot-gallery/](url)

**Comment by LinuxDonald** [comment]
Thanks for the report we will fix that.

**Comment by LinuxDonald** [comment]
We have an new forum.
