### ISSUE TITLE
"Media" and "About" links from forum page broken

### ISSUE THREAD

**Issue by CH4Code** [unknown-horizons/unknown-horizons.github.io#22]
![image](https://user-images.githubusercontent.com/16046997/60656723-4002ac00-9e50-11e9-877a-bb3b8ee0aad4.png)
Hi,
just noticed this small error on the Unknown Horizons forums.
Clicking the link "Media" or the "About" link from the forums page shows a 404 - page not found error. The same pages are accessable on the homepage without errors, but not directly from the forums.
Cheers

**Comment by LinuxDonald** [comment]
We have now an new forum.
