### ISSUE TITLE
Fix forum link

### ISSUE THREAD

**Issue by Wuzzy2** [unknown-horizons/unknown-horizons.github.io#23]
(continuation of <https://github.com/unknown-horizons/unknown-horizons/issues/2931>)

Please fix the forum link on http://unknown-horizons.org/get-involved/

This is the link to the new forum:
https://forum.freegamedev.net/viewforum.php?f=100

**Comment by LinuxDonald** [comment]
I will fix in the next days.

**Comment by LinuxDonald** [comment]
Sorry forgot it. I will fix this this week.
